apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: sre-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: my-webapp:latest
        imagePullPolicy: Never   # ✅ This tells K8s to use the local image in the node
        ports:
        - containerPort: 8080
